# This is a basic workflow to help you get started with Actions

name: CI Recomendation Qa.Coders

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Step 1 Verificar versão do Newman e Node
        run: 
          newman --version
          node --version

      - name: Step 2 Instalar Newman-Reporter-Htmlextra
        run: 
          sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 executar a coleção Recomendation
        run: newman run ./Recomendation.json -e ./RecomendationQa.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./newman/Report.html


      - name: Step 4 Produção de arquivos artefatos
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./newman/Report.html 
